version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

executors:
  build-and-test:
    docker:
      - image: circleci/node:12.13-browsers

jobs:
  build-and-test:
    executor: build-and-test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: CYPRESS_CACHE_FOLDER=~/repo/cypress_cache npm install --frozen-lockfile
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run mock Api for integration tests
          command: npm run stub-test-requests
          background: true
      - run:
          name: Run test server for integration tests
          command: npm run start-test-mode
          background: true
      - run:
          name: Run integration tests
          command: |
            export HELP_REQUESTS_API_URL=http://localhost:8080/help-requests
            export HELP_REQUESTS_CALLBACK_API_URL=http://localhost:8080/help-requests/callbacks
            export FOOD_REQUESTS_API_KEY=${FOOD_REQUESTS_API_KEY}
            export FOOD_REQUESTS_API_URL=${FOOD_REQUESTS_API_URL}
            export HELP_REQUESTS_API_KEY=
            export ADDRESSES_API_URL=${ADDRESSES_API_URL}
            export ADDRESSES_API_KEY=${ADDRESSES_API_KEY}
            export TOKEN_NAME=${TOKEN_NAME}
            export HACKNEY_JWT_SECRET=${HACKNEY_JWT_SECRET}
            export AUTHORISED_USER_GROUP=abc
            export AUTHORISED_ADMIN_GROUP=abc
            export LOCAL=true
            export LOCAL_USER_NAME='Joe Bloggs'
            export LOCAL_IS_ADMIN=true
            export MANAGE_FOOD_REQUESTS_ENABLED=true
            export MANAGE_HELP_REQUESTS_ENABLED=true
            export PAPERTRAIL_API_TOKEN=${PAPERTRAIL_API_TOKEN}
            export TOKEN_NAME=${TOKEN_NAME}
            CYPRESS_CACHE_FOLDER=~/repo/cypress_cache npm run cypress:run
      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build-and-test
