version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

executors:
  build-and-test:
    docker:
      - image: circleci/node:12.13-browsers

jobs:
  build-and-test:
    executor: build-and-test
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --frozen-lockfile
      - run:
          name: Run unit tests
          command: npm run test
      - aws-cli/setup:
          aws-access-key-id: CYPRESS_AWS_ACCESS_KEY_ID
          aws-secret-access-key: CYPRESS_AWS_SECRET_ACCESS_KEY
          aws-region: CYPRESS_AWS_REGION
      - run:
          name: Run integration tests
          command: |
            export HELP_REQUESTS_API_URL=http://localhost:8080/help-requests
            export HELP_REQUESTS_CALLBACK_API_URL=http://localhost:8080/help-requests/callbacks
            export HELP_REQUESTS_API_KEY=
            export ADDRESSES_API_URL=${ADDRESSES_API_URL}
            export ADDRESSES_API_KEY=${ADDRESSES_API_KEY}
            export TOKEN_NAME=${TOKEN_NAME}
            export HACKNEY_JWT_SECRET=${HACKNEY_JWT_SECRET}
            export AUTHORISED_USER_GROUP=abc
            export AUTHORISED_ADMIN_GROUP=abc
            export LOCAL=true
            export LOCAL_USER_NAME='Joe Bloggs'
            export LOCAL_IS_ADMIN=true
            export MANAGE_FOOD_REQUESTS_ENABLED=false
            export MANAGE_HELP_REQUESTS_ENABLED=true
            export PAPERTRAIL_API_TOKEN=${PAPERTRAIL_API_TOKEN}
            export TOKEN_NAME=${TOKEN_NAME}
            CYPRESS_CACHE_FOLDER=~/repo/cypress_cache yarn run int-test
      - store_artifacts:
          path: ~/repo/cypress/screenshots
      - store_artifacts:
          path: ~/repo/cypress/videos

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build-and-test
